# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded TextList 1.0 [list source [file join $dir listbox.tcl]]
package ifneeded attrib 1.0 [list source [file join $dir attrib.tcl]]
package ifneeded balloon 1.0 [list source [file join $dir balloon.tcl]]
package ifneeded colloc 1.0 [list source [file join $dir colloc.tcl]]
package ifneeded combobox 1.0 [list source [file join $dir combobox.tcl]]
package ifneeded commlib 1.0 [list source [file join $dir commlib.tcl]]
package ifneeded concord 1.0 [list source [file join $dir concord.tcl]]
package ifneeded corpus 1.0 [list source [file join $dir corpus.tcl]]
package ifneeded detail 1.0 [list source [file join $dir detail.tcl]]
package ifneeded freq 1.0 [list source [file join $dir freq.tcl]]
package ifneeded graph 1.0 [list source [file join $dir graph.tcl]]
package ifneeded gui 1.0 [list source [file join $dir gui.tcl]]
package ifneeded listres 1.0 [list source [file join $dir listres.tcl]]
package ifneeded menu 1.0 [list source [file join $dir menulib.tcl]]
package ifneeded mltlist 1.0 [list source [file join $dir mltlist.tcl]]
package ifneeded notebook 1.0 [list source [file join $dir notebook.tcl]]
package ifneeded outres 1.0 [list source [file join $dir outres.tcl]]
package ifneeded query 1.0 [list source [file join $dir query.tcl]]
package ifneeded result 1.0 [list source [file join $dir result.tcl]]
package ifneeded setopt 1.0 [list source [file join $dir setopt.tcl]]
package ifneeded sort 1.0 [list source [file join $dir sort.tcl]]
package ifneeded tools 1.0 [list source [file join $dir tools.tcl]]
package ifneeded widlist 1.0 [list source [file join $dir widlist.tcl]]
package ifneeded wordlist 1.0 [list source [file join $dir wordlist.tcl]]
